import type { Metadata } from "next";
import { absoluteUrl, canonical, site } from "@/lib/site.config";

interface PageMetaInput {
  title: string;
  description: string;
  path: string;
  /**
   * Explicit social-share image (e.g. a practice photo). When omitted, the page
   * falls back to the branded card generated by `src/app/opengraph-image.tsx`
   * via Next's file convention — so we deliberately do NOT set OG images here.
   */
  image?: string;
  noindex?: boolean;
  /** "article" for blog posts (adds published/modified time). Default website. */
  ogType?: "website" | "article";
  publishedTime?: string;
  modifiedTime?: string;
}

/** One metadata builder. Every page calls this. */
export function buildMetadata({
  title,
  description,
  path,
  image,
  noindex = false,
  ogType = "website",
  publishedTime,
  modifiedTime,
}: PageMetaInput): Metadata {
  const url = canonical(path);
  const branded = path === "/" ? title : `${title} | ${site.brand}`;
  const ogImage = image ? absoluteUrl(image) : undefined;

  return {
    title: path === "/" ? { absolute: title } : title,
    description,
    alternates: { canonical: url },
    robots: noindex
      ? { index: false, follow: true }
      : { index: true, follow: true },
    openGraph: {
      type: ogType,
      siteName: site.legalName,
      title: branded,
      description,
      url,
      locale: site.locale,
      ...(ogType === "article" && publishedTime ? { publishedTime } : {}),
      ...(ogType === "article" && modifiedTime ? { modifiedTime } : {}),
      ...(ogImage ? { images: [{ url: ogImage, alt: title }] } : {}),
    },
    twitter: {
      card: "summary_large_image",
      title: branded,
      description,
      ...(ogImage ? { images: [ogImage] } : {}),
    },
  };
}
